version: 2
jobs:
  build:
    docker:
      - image: microsoft/dotnet:2.1-sdk
<<<<<<< HEAD

=======
>>>>>>> 146ecf52eadd61b3d0c4743d3baae63bf1f76ead
    working_directory: ~/FinalProject/SecretProject
    working_directory: ~/SecretProject
    steps:
      - checkout
      - run:
        name: Debug location
        command: pwd
      - run:
          name: Restore packages for all projects in solution
          command: dotnet restore SecretProject
      - run:
          name: Build all projects in solution
          command: dotnet build SecretProject

    working_directory: ~/Final/SecretProject
    steps:
      - checkout
      - run: 
          name: Debug Location
          command: pwd
      - run:
          name: Restore packages for all projects in solution
          command: dotnet restore 
      - run:
          name: Build all projects in solution
          command: dotnet build 
      - run:
          name: Run tests in test project
          command: dotnet test GroupAppTest/GroupAppTest.csproj
          command: dotnet build
<<<<<<< HEAD

=======
>>>>>>> 146ecf52eadd61b3d0c4743d3baae63bf1f76ead
    working_directory: ~/SecretProject
    steps:
      - checkout
      - run:
          name: Restore packages for all projects in solution
          command: dotnet restore    
      - run:
          name: Build all projects in solution
          command: dotnet build 
      - run:
          name: Restore packages for all projects in solution
          command: dotnet restore   
      - run:
          name: Build all projects in solution
<<<<<<< HEAD
          command: dotnet build GroupApp
=======
          command: dotnet build
>>>>>>> 146ecf52eadd61b3d0c4743d3baae63bf1f76ead
